# Generated by Django 2.2.2 on 2019-06-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_url', models.URLField(max_length=300)),
                ('request_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
