# Generated by Django 2.2.2 on 2019-06-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3_converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='video_title',
            field=models.CharField(default='null', max_length=500),
        ),
    ]
