# Generated by Django 2.2.2 on 2019-06-24 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp3_converter', '0002_audiofile_video_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='audio_url',
            new_name='url',
        ),
    ]
