# Generated by Django 2.2.2 on 2019-06-26 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3_converter', '0003_auto_20190624_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='email',
            field=models.EmailField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='request_sent',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 26, 14, 41, 9, 936707)),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
